# label2id version 1 DO NOT USE WITH THE CURRENT VERSION OF AM 
"""
label2id = {
    'O': 0,
    'B-CITY': 1,
    'I-CITY': 2,
    'B-SOCIALNUM': 3,
    'I-SOCIALNUM': 4,
    'B-CREDITCARDNUMBER': 5,
    'I-CREDITCARDNUMBER': 6,
    'B-EMAIL': 7,
    'I-EMAIL': 8,
    'B-IDCARDNUM': 9,
    'I-IDCARDNUM': 10,
    'B-GIVENNAME': 11,
    'I-GIVENNAME': 12,
    'B-BUILDINGNUM': 13,
    'B-PASSWORD': 14,
    'I-PASSWORD': 15,
    'B-USERNAME': 16,
    'I-USERNAME': 17,
    'B-TAXNUM': 18,
    'I-TAXNUM': 19,
    'B-SURNAME': 20,
    'I-SURNAME': 21,
    'B-STREET': 22,
    'I-STREET': 23,
    'B-ZIPCODE': 24,
    'I-ZIPCODE': 25,
    'B-DATEOFBIRTH': 26,
    'I-DATEOFBIRTH': 27,
    'B-TELEPHONENUM': 28,
    'I-TELEPHONENUM': 29,
    'B-ACCOUNTNUM': 30,
    'I-ACCOUNTNUM': 31,
    'B-DRIVERLICENSENUM': 32,
    'I-DRIVERLICENSENUM': 33,
    'I-BUILDINGNUM': 34
}
"""
# id2label version 1 DO NOT USE WITH THE CURRENT VERSION OF AM
"""
id2label = {
    0: 'O',
    1: 'B-CITY',
    2: 'I-CITY',
    3: 'B-SOCIALNUM',
    4: 'I-SOCIALNUM',
    5: 'B-CREDITCARDNUMBER',
    6: 'I-CREDITCARDNUMBER',
    7: 'B-EMAIL',
    8: 'I-EMAIL',
    9: 'B-IDCARDNUM',
    10: 'I-IDCARDNUM',
    11: 'B-GIVENNAME',
    12: 'I-GIVENNAME',
    13: 'B-BUILDINGNUM',
    14: 'B-PASSWORD',
    15: 'I-PASSWORD',
    16: 'B-USERNAME',
    17: 'I-USERNAME',
    18: 'B-TAXNUM',
    19: 'I-TAXNUM',
    20: 'B-SURNAME',
    21: 'I-SURNAME',
    22: 'B-STREET',
    23: 'I-STREET',
    24: 'B-ZIPCODE',
    25: 'I-ZIPCODE',
    26: 'B-DATEOFBIRTH',
    27: 'I-DATEOFBIRTH',
    28: 'B-TELEPHONENUM',
    29: 'I-TELEPHONENUM',
    30: 'B-ACCOUNTNUM',
    31: 'I-ACCOUNTNUM',
    32: 'B-DRIVERLICENSENUM',
    33: 'I-DRIVERLICENSENUM',
    34: 'I-BUILDINGNUM'
}
"""

# label2id current version
label2id = {
    'O': 0,
    'B-DRIVERLICENSENUM': 1,
    'I-DRIVERLICENSENUM': 2,
    'B-DATEOFBIRTH': 3,
    'I-DATEOFBIRTH': 4,
    'B-ZIPCODE': 5,
    'I-ZIPCODE': 6,
    'B-TAXNUM': 7,
    'I-TAXNUM': 8,
    'B-BUILDINGNUM': 9,
    'B-TELEPHONENUM': 10,
    'I-TELEPHONENUM': 11,
    'B-SURNAME': 12,
    'I-SURNAME': 13,
    'B-EMAIL': 14,
    'I-EMAIL': 15,
    'B-SOCIALNUM': 16,
    'I-SOCIALNUM': 17,
    'B-GIVENNAME': 18,
    'I-GIVENNAME': 19,
    'B-PASSWORD': 20,
    'I-PASSWORD': 21,
    'B-CITY': 22,
    'I-BUILDINGNUM': 23,
    'B-IDCARDNUM': 24,
    'I-IDCARDNUM': 25,
    'B-ACCOUNTNUM': 26,
    'I-ACCOUNTNUM': 27,
    'B-USERNAME': 28,
    'I-USERNAME': 29,
    'I-CITY': 30,
    'B-STREET': 31,
    'I-STREET': 32,
    'B-CREDITCARDNUMBER': 33,
    'I-CREDITCARDNUMBER': 34
}

# id2label current version
id2label = {
    0: 'O',
    1: 'B-DRIVERLICENSENUM',
    2: 'I-DRIVERLICENSENUM',
    3: 'B-DATEOFBIRTH',
    4: 'I-DATEOFBIRTH',
    5: 'B-ZIPCODE',
    6: 'I-ZIPCODE',
    7: 'B-TAXNUM',
    8: 'I-TAXNUM',
    9: 'B-BUILDINGNUM',
    10: 'B-TELEPHONENUM',
    11: 'I-TELEPHONENUM',
    12: 'B-SURNAME',
    13: 'I-SURNAME',
    14: 'B-EMAIL',
    15: 'I-EMAIL',
    16: 'B-SOCIALNUM',
    17: 'I-SOCIALNUM',
    18: 'B-GIVENNAME',
    19: 'I-GIVENNAME',
    20: 'B-PASSWORD',
    21: 'I-PASSWORD',
    22: 'B-CITY',
    23: 'I-BUILDINGNUM',
    24: 'B-IDCARDNUM',
    25: 'I-IDCARDNUM',
    26: 'B-ACCOUNTNUM',
    27: 'I-ACCOUNTNUM',
    28: 'B-USERNAME',
    29: 'I-USERNAME',
    30: 'I-CITY',
    31: 'B-STREET',
    32: 'I-STREET',
    33: 'B-CREDITCARDNUMBER',
    34: 'I-CREDITCARDNUMBER'
}